# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

pod 'Firebase/Core', '~> 5.11.0'

pod 'GoogleAppMeasurement', '~> 5.3.0'

pod 'Firebase/Messaging', '~> 5.11.0'

target 'VincoReact' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for VincoReact

  target 'VincoReact-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'VincoReactTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
